name: Check PR Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Description
        id: check_description
        run: |
          description=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH")
          if [[ "$description" == *"## Changelog"* ]]; then
            echo "::set-output name=containsChangelog::true"
          else
            echo "::set-output name=containsChangelog::false"
          fi

      - name: Display result
        run: |
          echo "PR contains Changelog section: ${{ steps.check_description.outputs.containsChangelog }}"
