name: Check Changelog Section in PR Description
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog-section:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      PULL_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch PR description
        id: fetch-pr-description
        run: |
          description=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/$OWNER/$REPO/pulls/$PULL_NUMBER | jq -r '.body')
          echo "::set-output name=description::${description}"
          echo "PR Description: $description"
          
      - name: Check for Changelog Section
        run: |
          description="${{ steps.fetch-pr-description.outputs.description }}"
          echo "Checking PR Description for Changelog section..."
          if echo "$description" | grep -q '## Changelog'; then
            echo "Changelog section found in PR description."
          else
            echo "Changelog section not found in PR description."
            exit 1
          fi
