# name: Check Changelog.md
# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
# jobs:
#   check-changelog:
#      runs-on: ubuntu-latest
#      permissions: write-all
#      steps:
#           - uses: actions/checkout@v4
#           - name: Fetch changed files
#             id: fetch-changed-files
#             run: |
#               response=$(gh api \
#               -H "Accept: application/vnd.github+json" \
#               -H "X-GitHub-Api-Version: 2022-11-28" \
#                repos/${owner}/${REPO}/pulls/${PULL_NUMBER}/files)
#               echo "$response" | jq '.' > response.json
              
          
#           
#           - name: Check if Changelog.md is changed
#             run: |
#               if [[ $(jq '.[].filename' response.json) == *"CHANGELOG.md"* ]]; then
#                 echo "Changelog.md is changed"
#                 exit 0
#               else
#                 echo "Changelog.md is not changed"
#                 exit 1
#               fi
name: Check Changelog Section in PR Description
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog-section:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      PULL_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch PR description
        id: fetch-pr-description
        run: |
          description=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/$OWNER/$REPO/pulls/$PULL_NUMBER | jq -r '.body')
          echo "::set-output name=description::${description}"
          echo "PR Description: $description"
          
      - name: Check for Changelog Section
        run: |
          description="${{ steps.fetch-pr-description.outputs.description }}"
          if echo "$description" | grep -q '<## Changelog'; then
            echo "Changelog section found in PR description."
            exit 0
          else
            echo "Changelog section not found in PR description."
            exit 1
          fi

