name: Check Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-section:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check for section
      run: |
        section_exists=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3.raw" \
                        ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files \
                        | grep "## Changelog" \
                        | wc -l)
        
        if [ "$section_exists" -gt "0" ]; then
          echo "Section found!"
        else
          echo "Section not found."
          exit 1
        fi
