name: Check PR for Changelog

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR Description
        id: check_description
        run: |
          description=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH")
          if [[ "$description" == *"## Changelog"* ]]; then
            echo "containsChangelog=true" >> $GITHUB_OUTPUT
            echo "true" > containsChangelog.txt
          else
            echo "containsChangelog=false" >> $GITHUB_OUTPUT
            echo "false" > containsChangelog.txt
          fi
      - name: Exit with appropriate code
        run: |
          if [[ "${{ steps.check_description.outputs.containsChangelog }}" == "true" ]]; then
            echo "PR contains Changelog section"
            exit 0
          else
            echo "PR does not contain Changelog section"
            exit 1
          fi
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-description-info
          path: containsChangelog.txt
          if-no-files-found: error