name: Check Changelog Section in PR Description
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changelog-section:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract PR Description
        id: extract-description
        run: echo "::set-output name=description::${{ github.event.pull_request.body }}"

      - name: Check for Changelog Section
        run: |
          description="${{ steps.extract-description.outputs.description }}"
          echo "Checking PR Description for Changelog section..."
          if echo "$description" | grep -q '## Changelog'; then
            echo "Changelog section found in PR description."
          else
            echo "Changelog section not found in PR description."
            exit 1
          fi
