name: Javascript Tests

on: [push, pull_request]

jobs:
  pre_job:
    name: Path match check
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths: '["**.vue", "**.js", "yarn.lock"]'
  test:
    name: Frontend tests
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
    - name: Install dependencies
      run: |
        yarn --frozen-lockfile
        npm rebuild node-sass
    - name: Run tests
      run: yarn test

  visual_tests:
    name: Frontend Visual Tests
    needs: test
    if: ${{ github.event_name == 'pull_request' && needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      percy_url: ${{ steps.extract-url.outputs.percy_url }}
      total_tests: ${{ steps.parse_results.outputs.total_tests }}
      passed_tests: ${{ steps.parse_results.outputs.passed_tests }}
      failed_tests: ${{ steps.parse_results.outputs.failed_tests }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          npm rebuild node-sass
      - name: Start server
        run: |
          yarn dev &
          sleep 60 &&
          curl -sSf http://localhost:4000/testing-playground
        env:
          SHELL: /bin/bash
      - name: Run visual tests
        id: run-visual-tests
        run: |
          yarn test:percy 2>&1 | tee test-output.log
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Extract Percy build URL
        id: extract-url
        run: |
          url=$(grep -o 'https://percy.io/[a-zA-Z0-9/_-]*' test-output.log | tail -1)
          echo "PERCY_BUILD_URL=$url" >> $GITHUB_ENV
          echo "percy_url=$url" >> $GITHUB_OUTPUT
          echo "Percy build URL: $url"
      - name: Check extracted Percy URL
        run: |
          echo "Extracted Percy URL: ${{ steps.extract-url.outputs.percy_url }}"
      - name: Parse Test Results
        id: parse_results
        run: |
          TOTAL_TESTS=$(grep -oP 'Tests:\s+\K\d+' test_output.log)
          PASSED_TESTS=$(grep -oP 'Tests:\s+\d+\s+passed\s+\(\K\d+' test_output.log)
          FAILED_TESTS=$((TOTAL_TESTS - PASSED_TESTS))
          echo "total_tests=$TOTAL_TESTS" >> $GITHUB_OUTPUT
          echo "passed_tests=$PASSED_TESTS" >> $GITHUB_OUTPUT
          echo "failed_tests=$FAILED_TESTS" >> $GITHUB_OUTPUT
    
  comment:
    name: Comment Percy results
    needs: visual_tests
    if: ${{ needs.visual_tests.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Percy URL
        run: | 
          echo "Percy URL: ${{ needs.visual_tests.outputs.percy_url }}"
      - name: Post results comment
        uses: thollander/actions-comment-pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_BUILD_URL: ${{ env.PERCY_BUILD_URL }}
        with:
          message: |
            ### Percy Visual Test Results
            **Percy Dashboard:** [View Detailed Report](${{ needs.visual_tests.outputs.percy_url }})

            **Summary:**
            - **Total Tests Run:** ${{ needs.visual_tests.outputs.total_tests }}
            - **Tests Passed:** ${{ needs.visual_tests.outputs.passed_tests }}
            - **Tests Failed:** ${{ needs.visual_tests.outputs.failed_tests }}

            **Environment:**
            - **Node.js Version:** 18.x
            - **OS:** Ubuntu-latest

            **Instructions for Reviewers:**
            - Click on the [Percy Dashboard](${{ needs.visual_tests.outputs.percy_url }}) link to view detailed visual diffs.
            - Review the visual changes highlighted in the report.
            - Approve or request changes based on the visual differences.
          comment_tag: execution
          mode: recreate