name: Update Changelog.md

on:
  pull_request:
    types:
      - closed

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Check if PR is from dependabot
        id: check-dependabot
        run: |
          is_dependabot=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
          echo "is_dependabot=$is_dependabot" >> $GITHUB_OUTPUT
        
      - name: Extract and update Changelog
        id: modify-changelog
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          pr_link="[#${pr_number}]"
          pr_link_ref="[#${pr_number}]: ${{ github.event.pull_request.html_url }}"

          if [ "${{ steps.check-dependabot.outputs.is_dependabot }}" == "dependabot[bot]" ]; then
            changelog="- **Description:** ${{ github.event.pull_request.title }}\n  - **Products impact:** Dev Dependency upgrade\n  - **Addresses:** -\n  - **Components:** -\n  - **Breaking:** -\n  - **Impacts a11y:** -\n  - **Guidance:** -"
          else
            description=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH" | awk '/<!-- [DO NOT REMOVE-USED BY GH ACTION] CHANGELOG START -->/{flag=1; next} /<!-- [DO NOT REMOVE-USED BY GH ACTION] CHANGELOG END -->/{flag=0} flag')
            pr_link_formatted=$(echo "$pr_link" | sed 's/\//\\\//g') # Escape slashes for sed
            description_with_links=$(echo "$description" | sed "/- \*\*Description:\*\*/{s//- $pr_link_formatted\n  - **Description:**/;:a;n;ba}")
            changelog_section=$(echo "$description_with_links" | sed '/<!--/,/-->/d' | sed '/<!--/,/-->/d' | sed '1d;$d')
            changelog="${changelog_section}"
          fi

          echo "${changelog}" > changelog_output.txt
          awk '/<!-- \[DO NOT REMOVE-USED BY GH ACTION\] PASTE CHANGELOG -->/{print; system("cat changelog_output.txt"); next} 1' CHANGELOG.md > tmpfile && mv tmpfile CHANGELOG.md
        
      - name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            branch: ${{ github.event.pull_request.base.ref }}
            commit_message: "Update CHANGELOG.md w/ PR #${{ github.event.pull_request.number }}"
            file_pattern: CHANGELOG.md